backend:
    name: github
    branch: main # Branch para publicação (opcional; padrão é master)

media_folder: 'public/images/uploads' # Pasta onde os arquivos de mídia serão armazenados
public_folder: '/images/uploads' # O caminho público para os arquivos de mídia

collections:
    - name: 'blog' # Used in routes, e.g., /admin/collections/blog
      label: 'Blog' # Used in the UI
      folder: 'src/content/blog' # The path to the folder where the documents are stored
      media_folder: 'src/assets/images' # Location where files will be stored in the repo
      public_folder: 'src/assets/images' # The src attribute for uploaded media
      create: true # Allow users to create new documents in this collection
      fields: # The fields for each document, usually in frontmatter
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
          - { label: 'Título', name: 'title', widget: 'string' }
          - { label: 'Data de Publicação', name: 'date', widget: 'datetime' }
          - { label: 'Imagem Destacada', name: 'thumbnail', widget: 'image' }
          - { label: 'Rating (escala de 1-5)', name: 'rating', widget: 'number' }
          - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
